# Generated by Django 5.1.9 on 2025-06-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0002_alter_post_date_alter_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="suggested_reads",
            field=models.ManyToManyField(blank=True, to="postapp.post"),
        ),
    ]
