# Generated by Django 5.1.9 on 2025-06-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0003_post_suggested_reads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="suggested_reads",
        ),
        migrations.AddField(
            model_name="post",
            name="suggested",
            field=models.BooleanField(default=False),
        ),
    ]
